let produtos = [
    {id: 1, nome: "Detergente", setor: "limpeza", preco: 12.99, marca: "Ype"},
    {id: 2, nome: "Detergente", setor: "limpeza", preco: 13.50, marca: "Minuano"},
    {id: 3, nome: "Detergente", setor: "limpeza", preco: 11.99, marca: "Limpol"},
    {id: 4, nome: "Sabao em Po", setor: "limpeza", preco: 18.50, marca: "Omo"},
    {id: 5, nome: "Sabao em Po", setor: "limpeza", preco: 17.99, marca: "Ariel"},
    {id: 6, nome: "Sabao em Po", setor: "limpeza", preco: 16.99, marca: "Tixan"},
    {id: 7, nome: "Amaciante", setor: "limpeza", preco: 10.90, marca: "Comfort"},
    {id: 8, nome: "Amaciante", setor: "limpeza", preco: 9.99, marca: "Downy"},
    {id: 9, nome: "Amaciante", setor: "limpeza", preco: 11.50, marca: "Fofo"},
    {id: 10, nome: "Desinfetante", setor: "limpeza", preco: 8.99, marca: "Veja"},
    {id: 11, nome: "Desinfetante", setor: "limpeza", preco: 7.99, marca: "Lysoform"},
    {id: 12, nome: "Desinfetante", setor: "limpeza", preco: 8.50, marca: "Pinho Sol"},
    {id: 13, nome: "Agua Sanitaria", setor: "limpeza", preco: 4.99, marca: "Qboa"},
    {id: 14, nome: "Agua Sanitaria", setor: "limpeza", preco: 5.50, marca: "Brilux"},
    {id: 15, nome: "Agua Sanitaria", setor: "limpeza", preco: 4.50, marca: "Candura"},
    {id: 16, nome: "Shampoo", setor: "higiene", preco: 15.99, marca: "Pantene"},
    {id: 17, nome: "Shampoo", setor: "higiene", preco: 14.99, marca: "Seda"},
    {id: 18, nome: "Shampoo", setor: "higiene", preco: 13.99, marca: "Elseve"},
    {id: 19, nome: "Condicionador", setor: "higiene", preco: 16.99, marca: "Pantene"},
    {id: 20, nome: "Condicionador", setor: "higiene", preco: 15.99, marca: "Seda"},
    {id: 21, nome: "Condicionador", setor: "higiene", preco: 14.99, marca: "Elseve"},
    {id: 22, nome: "Sabonete", setor: "higiene", preco: 2.50, marca: "Dove"},
    {id: 23, nome: "Sabonete", setor: "higiene", preco: 1.99, marca: "Lux"},
    {id: 24, nome: "Sabonete", setor: "higiene", preco: 2.30, marca: "Nivea"},
    {id: 25, nome: "Papel Higienico", setor: "higiene", preco: 9.90, marca: "Neve"},
    {id: 26, nome: "Papel Higienico", setor: "higiene", preco: 8.99, marca: "Personal"},
    {id: 27, nome: "Papel Higienico", setor: "higiene", preco: 7.99, marca: "Duo"},
    {id: 28, nome: "Creme Dental", setor: "higiene", preco: 6.50, marca: "Colgate"},
    {id: 29, nome: "Creme Dental", setor: "higiene", preco: 5.99, marca: "Oral-B"},
    {id: 30, nome: "Creme Dental", setor: "higiene", preco: 6.20, marca: "Sensodyne"},
    {id: 31, nome: "Desodorante", setor: "higiene", preco: 11.99, marca: "Rexona"},
    {id: 32, nome: "Desodorante", setor: "higiene", preco: 10.99, marca: "Nivea"},
    {id: 33, nome: "Desodorante", setor: "higiene", preco: 12.50, marca: "Dove"},
    {id: 34, nome: "Arroz", setor: "alimentos", preco: 19.99, marca: "Tio Joao"},
    {id: 35, nome: "Arroz", setor: "alimentos", preco: 18.50, marca: "Camil"},
    {id: 36, nome: "Arroz", setor: "alimentos", preco: 17.99, marca: "Urbano"},
    {id: 37, nome: "Feijao", setor: "alimentos", preco: 7.99, marca: "Camil"},
    {id: 38, nome: "Feijao", setor: "alimentos", preco: 8.50, marca: "Kicaldo"},
    {id: 39, nome: "Feijao", setor: "alimentos", preco: 7.50, marca: "Caldo Bom"},
    {id: 40, nome: "Acucar", setor: "alimentos", preco: 3.99, marca: "Uniao"},
    {id: 41, nome: "Acucar", setor: "alimentos", preco: 3.50, marca: "Guarani"},
    {id: 42, nome: "Acucar", setor: "alimentos", preco: 3.20, marca: "Caravelas"},
    {id: 43, nome: "Cafe", setor: "alimentos", preco: 12.50, marca: "Pirao"},
    {id: 44, nome: "Cafe", setor: "alimentos", preco: 11.99, marca: "Melitta"},
    {id: 45, nome: "Cafe", setor: "alimentos", preco: 13.50, marca: "3 Coracoes"},
    {id: 46, nome: "Macarrao", setor: "alimentos", preco: 4.50, marca: "Renata"},
    {id: 47, nome: "Macarrao", setor: "alimentos", preco: 4.99, marca: "Barilla"},
    {id: 48, nome: "Macarrao", setor: "alimentos", preco: 4.20, marca: "Adria"},
    {id: 49, nome: "Oleo de Soja", setor: "alimentos", preco: 8.99, marca: "Soya"},
    {id: 50, nome: "Oleo de Soja", setor: "alimentos", preco: 8.50, marca: "Liza"},
    {id: 51, nome: "Oleo de Soja", setor: "alimentos", preco: 8.20, marca: "Leve"},
    {id: 52, nome: "Leite", setor: "alimentos", preco: 4.20, marca: "Parmalat"},
    {id: 53, nome: "Leite", setor: "alimentos", preco: 3.99, marca: "Italac"},
    {id: 54, nome: "Leite", setor: "alimentos", preco: 4.50, marca: "Piracanjuba"},
    {id: 55, nome: "Achocolatado", setor: "alimentos", preco: 6.99, marca: "Nescau"},
    {id: 56, nome: "Achocolatado", setor: "alimentos", preco: 6.50, marca: "Toddy"},
    {id: 57, nome: "Achocolatado", setor: "alimentos", preco: 6.20, marca: "Maguary"},
    {id: 58, nome: "Biscoito", setor: "alimentos", preco: 3.50, marca: "Trakinas"},
    {id: 59, nome: "Biscoito", setor: "alimentos", preco: 3.99, marca: "Passatempo"},
    {id: 60, nome: "Biscoito", setor: "alimentos", preco: 3.20, marca: "Negresco"},
    {id: 61, nome: "Cereal", setor: "alimentos", preco: 9.99, marca: "Nestle"},
    {id: 62, nome: "Cereal", setor: "alimentos", preco: 9.50, marca: "Kelloggs"},
    {id: 63, nome: "Cereal", setor: "alimentos", preco: 8.99, marca: "Mae Terra"},
    {id: 64, nome: "Suco de Laranja", setor: "bebidas", preco: 5.99, marca: "Del Valle"},
    {id: 65, nome: "Suco de Laranja", setor: "bebidas", preco: 5.50, marca: "Maguary"},
    {id: 66, nome: "Suco de Laranja", setor: "bebidas", preco: 5.20, marca: "Sufresh"},
    {id: 67, nome: "Refrigerante", setor: "bebidas", preco: 6.50, marca: "Coca-Cola"},
    {id: 68, nome: "Refrigerante", setor: "bebidas", preco: 6.20, marca: "Pepsi"},
    {id: 69, nome: "Refrigerante", setor: "bebidas", preco: 5.99, marca: "Fanta"},
    {id: 70, nome: "Agua Mineral", setor: "bebidas", preco: 1.99, marca: "Crystal"},
    {id: 71, nome: "Agua Mineral", setor: "bebidas", preco: 1.80, marca: "Minalba"},
    {id: 72, nome: "Agua Mineral", setor: "bebidas", preco: 1.70, marca: "Bonafont"},
    {id: 73, nome: "Cerveja", setor: "bebidas", preco: 3.99, marca: "Skol"},
    {id: 74, nome: "Cerveja", setor: "bebidas", preco: 3.50, marca: "Brahma"},
    {id: 75, nome: "Cerveja", setor: "bebidas", preco: 4.20, marca: "Heineken"},
    {id: 76, nome: "Vinho", setor: "bebidas", preco: 29.90, marca: "Casillero del Diablo"},
    {id: 77, nome: "Vinho", setor: "bebidas", preco: 25.99, marca: "Miolo"},
    {id: 78, nome: "Vinho", setor: "bebidas", preco: 27.50, marca: "Salton"},
    {id: 79, nome: "Leite Condensado", setor: "alimentos", preco: 4.99, marca: "Moca"},
    {id: 80, nome: "Leite Condensado", setor: "alimentos", preco: 4.50, marca: "Piracanjuba"},
    {id: 81, nome: "Leite Condensado", setor: "alimentos", preco: 4.20, marca: "Italac"},
    {id: 82, nome: "Creme de Leite", setor: "alimentos", preco: 3.99, marca: "Nestle"},
    {id: 83, nome: "Creme de Leite", setor: "alimentos", preco: 3.50, marca: "Italac"},
    {id: 84, nome: "Creme de Leite", setor: "alimentos", preco: 3.20, marca: "Piracanjuba"},
    {id: 85, nome: "Margarina", setor: "alimentos", preco: 5.99, marca: "Qualy"},
    {id: 86, nome: "Margarina", setor: "alimentos", preco: 5.50, marca: "Delicia"},
    {id: 87, nome: "Margarina", setor: "alimentos", preco: 5.20, marca: "Doriana"},
    {id: 88, nome: "Queijo", setor: "alimentos", preco: 14.99, marca: "Polenghi"},
    {id: 89, nome: "Queijo", setor: "alimentos", preco: 13.99, marca: "Quata"},
    {id: 90, nome: "Queijo", setor: "alimentos", preco: 12.99, marca: "Tirolez"},
    {id: 91, nome: "Maca", setor: "hortifruti", preco: 4.99, marca: "Frutaria"},
    {id: 92, nome: "Banana", setor: "hortifruti", preco: 3.29, marca: "Tropical"},
    {id: 93, nome: "Laranja", setor: "hortifruti", preco: 5.49, marca: "Vitafruit"},
    {id: 94, nome: "Tomate", setor: "hortifruti", preco: 6.99, marca: "HortiFruti"},
    {id: 95, nome: "Cenoura", setor: "hortifruti", preco: 2.79, marca: "Campo Verde"},
    {id: 96, nome: "Batata", setor: "hortifruti", preco: 4.49, marca: "Sabor do Campo"},
    {id: 97, nome: "Brocolis", setor: "hortifruti", preco: 7.99, marca: "Verde Vida"},
    {id: 98, nome: "Pepino", setor: "hortifruti", preco: 3.59, marca: "Horta Natural"},
    {id: 99, nome: "Alface", setor: "hortifruti", preco: 2.99, marca: "FreshLeaf"},
    {id: 100, nome: "Abobrinha", setor: "hortifruti", preco: 3.89, marca: "Verde Puro"},
    {id: 101, nome: "Pimentao", setor: "hortifruti", preco: 5.79, marca: "HortiPimentas"},
    {id: 102, nome: "Uva", setor: "hortifruti", preco: 9.49, marca: "Frutal"},
    {id: 103, nome: "Melancia", setor: "hortifruti", preco: 8.99, marca: "Frutaria Premium"}
];


module.exports = produtos;